=== slieer/javaworks/simpleweb/WebContent/xml/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 (http://www.altova.com) -->
<xs:schema targetNamespace="contacts" xmlns="contacts"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="contacts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contact" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="contact">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="method" />
				<xs:element ref="contactname" />
				<xs:element ref="userid" />
				<xs:element ref="createdate" />
			</xs:sequence>
			<xs:attribute name="id"> <!--  use="required" -->
				<xs:simpleType>
					<xs:restriction base="xs:long"></xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="userid">
		<xs:simpleType>
			<xs:restriction base="xs:long"></xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="method">
		<xs:simpleType>
			<xs:restriction base="xs:decimal"></xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="createdate">
		<xs:simpleType>
			<xs:restriction base="xs:string"></xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="contactname">
		<xs:simpleType>
			<xs:restriction base="xs:string"></xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== slieer/javaworks/simpleweb/WebContent/xml/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns="contacts" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="contacts file:///E:/BorqsWorkspace/workspace/simpleweb/WebContent/xml/contacts.xsd">
	<contact id="21016">
		<method>8405566</method>
		<contactname>ALAN</contactname>
		<userid>6</userid>
		<createdate>2011-09-28 07:10:20</createdate>
	</contact>
	<contact id="21015">
		<method>13798584767</method>
		<contactname>ALAN</contactname>
		<userid>6</userid>
		<createdate>2011-09-28 07:10:20</createdate>
	</contact>
	<contact id="21053">
		<method>12593008613823514039</method>
		<contactname>Test1ghhhjj</contactname>
		<userid>6</userid>
		<createdate>2011-09-29 05:52:25</createdate>
	</contact>
	<contact id="21046">
		<method>84236457</method>
		<contactname>翟小斌</contactname>
		<userid>6</userid>
		<createdate>2011-09-28 07:10:20</createdate>
	</contact>
</contacts>
